version: '3.7'

services:
  backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8001:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/dist
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:
